---
version: '3.6'

{% import "macros.jinja" as macros with context %}

{% if elk %}
x-redis-def:
  &redis-def
  image: redis:alpine

x-elasticsearch-def:
  &elasticsearch-def
  build: ./elasticsearch
  environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "http.host=0.0.0.0"
    - "transport.host=127.0.0.1"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536
      hard: 65536
  cap_add:
    - IPC_LOCK

x-kibana-def:
  &kibana-def
  image: docker.elastic.co/kibana/kibana:7.9.3
  environment:
    ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    XPACK_MONITORING_ENABLED: "true"
    XPACK_MONITORING_COLLECTION_ENABLED: "true"
    SERVER_NAME: "localhost"
  depends_on:
    - elasticsearch
  links:
    - elasticsearch
  ports:
    - 5601:5601/tcp

x-logstash-def:
  &logstash-def
  build: ./logstash
  environment:
    - ES_HOST=http://elasticsearch:9200
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  depends_on:
    - redis
    - elasticsearch
  links:
    - redis
    - elasticsearch

x-filebeat-def:
  &filebeat-def
  build: ./filebeat
  environment:
    - ENV_NAME=dev
    - IP_ADDRESS=127.0.0.1
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  depends_on:
    - redis
  links:
    - redis
  volumes:
    - ./logs/besu/:/var/log/besu/
    - ./logs/orion/:/var/log/orion/    

x-metricbeat-def:
  &metricbeat-def
  build: ./metricbeat
  environment:
    - ENV_NAME=dev
    - IP_ADDRESS=127.0.0.1
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  depends_on:
    - redis
  links:
    - redis

{% endif %}

{% set anyRPCNode = nodeConfig | firstByAttr('type', 'rpc') %}

{% if enableETHSignerProxy and anyRPCNode %}
x-ethsignerProxy-def:
  &ethsignerProxy-def
  image: consensys/quorum-ethsigner:${QUORUM_ETHSIGNER_VERSION:-latest}
  command: [
    "--chain-id=1337",
    "--http-listen-host=0.0.0.0",
    "--downstream-http-port=8545",
    "--downstream-http-host=rpcnode",
    "file-based-signer",
    "-k",
    "/opt/ethsigner/keyfile",
    "-p",
    "/opt/ethsigner/passwordfile"
  ]
  ports:
    - 8545
{% endif %}

services:
{{ macros.proxies(nodeConfig) }}

{{ macros.firewalls(nodeConfig) }}

{{ macros.besuNodes(nodeConfig) }}

{% if enableETHSignerProxy and anyRPCNode %}
  ethsignerProxy:
    << : *ethsignerProxy-def
    volumes:
      - ./config/ethsigner/password:/opt/ethsigner/passwordfile
      - ./config/ethsigner/key:/opt/ethsigner/keyfile
    depends_on:
      - validator1
      - rpcnode
    ports:
      - 18545:8545/tcp
    networks:
      {{defaultNetwork}}:
{% if not enableDNS %}
        ipv4_address: 172.16.239.40
{% endif %}
{% endif %}

{% if not orchestrate and anyRPCNode %}
  explorer:
    build: block-explorer-light/.
    image: quorum-dev-quickstart/block-explorer-light:develop
    depends_on:
      - {{ anyRPCNode.name}}
    ports:
      - 25000:80/tcp
    networks:
      {{defaultNetwork}}:
{% if not enableDNS %}
        ipv4_address: 172.16.239.31
{% endif %}

{% if metrics %}
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    networks:
      {{defaultNetwork}}:
{% if not enableDNS %}
        ipv4_address: 172.16.239.32
{% endif %}

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    networks:
      {{defaultNetwork}}:
{% if not enableDNS %}
        ipv4_address: 172.16.239.33
{% endif %}
{% endif %}
{% endif %}

{% if elk %}
  redis:
    << : *redis-def
    networks:
      {{defaultNetwork}}:
{% if not enableDNS %}
        ipv4_address: 172.16.239.34
{% endif %}

  elasticsearch:
    << : *elasticsearch-def
    networks:
      {{defaultNetwork}}:
{% if not enableDNS %}
        ipv4_address: 172.16.239.35
{% endif %}

  kibana:
    << : *kibana-def
    networks:
      {{defaultNetwork}}:
{% if not enableDNS %}
        ipv4_address: 172.16.239.36
{% endif %}

  logstash:
    << : *logstash-def
    networks:
      {{defaultNetwork}}:
{% if not enableDNS %}
        ipv4_address: 172.16.239.37
{% endif %}

  filebeat:
    << : *filebeat-def
    networks:
      {{defaultNetwork}}:
{% if not enableDNS %}
        ipv4_address: 172.16.239.38      
{% endif %}

  metricbeat:
    << : *metricbeat-def
    networks:
      {{defaultNetwork}}:
{% if not enableDNS %}
        ipv4_address: 172.16.239.39 
{% endif %}

{% endif %}



volumes:
  public-keys:

  prometheus:

  grafana:

  cakeshop:

networks:
{% for network in networks %}
  {{network}}:
    driver: bridge
{%- if not enableDNS %}
    ipam:
      config:
        - subnet: 172.16.239.0/24
{% endif %}
{% endfor %}
